### PR TITLE
Update the curriculum dashboard to be easier to navigate

### LINKED ISSUE #278: Update the curriculum dashboard to be easier to navigate
# Overview

## Problem statement
There is currently a problem with how the [curriculum dashboard](https://www.toynet.projectreclass.org/dashboard/1?module=0) navigates. It is not clear to the user how to get to the actual submodule.

## Proposed solutions
Remove the collapsable description below the submodule title and just include the description without it being collapsable. 
Replace the "Go to submodule >" text with a play button.

# Acceptance criteria
- Submodule description is not collapsable and is visible by default
- The "Go to submodule" link is replaced with a Play button.

# Designs
Inspiration (ignore colors)
image (3)

# Related documents
- You can use [react-icons](https://react-icons.github.io/react-icons/) to find a good play button.

**Notice**
We recycle issues that have been stale for some time. Please refer to the [Contributing Documentation](https://docs.projectreclass.org/toynet/contributing-code-to-toynet/contributing-code-to-toynet) for more details as well as development best practices!

### PR DESCRIPTION
**Pull request by misakimichy**
Checkout the [Contribution Doc](https://docs.projectreclass.org/toynet/contributing-code-to-toynet/contributing-code-to-toynet) to make sure you're contributing correctly! :)

Follow this checklist for submitting a pull request (PR):

- [ ] Your ticket is a "Help Wanted" issue on GitHub for the project that you're contributing to.
- [x] Your branch is up-to-date with the main branch.
- [x] Your code follows the established code style defined in the ESLint rules.
- [x] You have included any relevant tests for the code that you're contributing.
- [x] You are submitting your PR against the main branch of the repository you are contributing to from your fork.
- [x] You have linked your GitHub issue at the **Resolves Issue** section if it exists.
- [x] You have provided a brief description of the issue.

## Description
- Updated 'Go to submodule >' text with a play button.
- Updated the text in the header.
- Updated a unit test.

**Resolves Issue**: closes #278.

### CODE REVIEW

**Comment by scottjr632** [comment]
Its looks good so far! Do you think you could also make the descriptions of the submodules be open by default as well?

**Comment by misakimichy** [comment]
Oh, all of the descriptions?

**Comment by scottjr632** [comment]
> Oh, all of the descriptions?

Yes 😄 If that's ok? We can always move that to another ticket. But it should be as easy as changing the default value in `SubModule.tsx` to true on line 52.

**Comment by misakimichy** [comment]
I’ll update the part! No need to create a new ticket, Scott :)

**Comment by misakimichy** [comment]
@scottjr632 I made an update for the descriptions of the submodules be open by default and added some stylings for the description. Please review!

**Review by scottjr632 — APPROVED** [review]
LGTM!

**Pull request merged**
