### PR TITLE
fixed panel jumping

### PR DESCRIPTION
**Pull request by SYChJung**
Checkout the [Engineer Workflow Doc](https://docs.google.com/presentation/d/1pdzuHG-yO7_qW6jiByaGTLztKZ6b72lBNqSdNT5WZQ8/edit) to make sure you're contributing correctly! :)

**[Tickets](https://trello.com/b/dYOQKJGv/reclass)** 
Trello Ticket: https://trello.com/c/7yO4f463/395-emulator-creating-links-causes-the-panel-to-jump
Additional Notes:

**[Dependencies](https://docs.google.com/document/d/1CM6OA2nlhI3DHnHdDEgySukx_tZ_wsG-C2YgraZRvJA/edit#heading=h.czpk4cbi7z4g)**

**[Explain Impact on DB](https://docs.google.com/document/d/1CM6OA2nlhI3DHnHdDEgySukx_tZ_wsG-C2YgraZRvJA/edit#heading=h.285lgcs4z84o)**

**[Testing](https://docs.google.com/document/d/1CM6OA2nlhI3DHnHdDEgySukx_tZ_wsG-C2YgraZRvJA/edit#heading=h.rs692kr58cf8)**

How did you test this? List of actions & expected behavior with helpful screenshots for reviewer:

If this change is performance related, please document what tests were / should be done to verify improvement:

### CODE REVIEW

**Comment by takakonishimura** [comment]
Thanks John, please list how you tested this change. :)

**Review by scottjr632 — CHANGES_REQUESTED** [review]
This looks good John!

Do you think you could add a gif of what bug this fixes and a gif of the fix?

**Comment by SYChJung** [comment]
Here is the gif files of the bug and the fixed.

This is the bug gif file I got from the trello ticket:
panel_jump_bug

Here is the gif file of the fixed version:
panel_jump_fixed

**Review by scottjr632 — APPROVED** [review]
Thanks for adding those gifs John! LGTM

**Pull request merged**
