### PR TITLE
Update maxW of Lectures and Articles to 700px #283

### LINKED ISSUE #283: Update max-width of Lectures and Articles to 700px
# Overview

## Problem statement
Currently, the max-width of the articles and lecture sub-modules makes it difficult to read. 

## Proposed solutions
Set the `max-width` of the article and lecture pages to be 700px.

**Notice**
We recycle issues that have been stale for some time. Please refer to the [Contributing Documentation](https://docs.projectreclass.org/toynet/contributing-code-to-toynet/contributing-code-to-toynet) for more details as well as development best practices!

### PR DESCRIPTION
**Pull request by 4-Leafs-Code**
Updated the maxW of Lectures and Articles to 700px

**Resolves Issue**: closes #283

### CODE REVIEW

**Comment by 4-Leafs-Code** [comment]
Huh! Wow, changing one simple value broke the code. I wonder why???... Well, I'll take another crack at it. May be it is because of the inline styling???

**Comment by scottjr632** [comment]
Looks like the jest snapshot tests are failing, can you update them by running `npm run test -- -u`?

**Comment by 4-Leafs-Code** [comment]
this is what I got: what do I push

No tests found related to files changed since last commit.
Press `a` to run all tests, or run Jest with `--watchAll`.

Watch Usage
 › Press a to run all tests.
 › Press f to run only failed tests.
 › Press q to quit watch mode.
 › Press p to filter by a filename regex pattern.
 › Press t to filter by a test name regex pattern.
 › Press Enter to trigger a test run.





________________________________

**Review by scottjr632 — APPROVED** [review]
LGTM, just update the snapshots and we can merge 🙂

[looksgood](https://app.graphite.dev/macros/Project-Reclass)

**Comment by 4-Leafs-Code** [comment]
Okay, I have created a new pull request. After I updated everything, changed the code, I ran npm test and passed everything still.

But the 2 .jsons were included in my pull request and it wouldn't let me remove them. Is this going to be a problem?

It's not a PR only a commit to my fork but please ignore the migrateSplashHeader. I'm not finished with that yet. I still have to fix the button size.
________________________________

**Pull request closed without merging**
